name: Deploy strapi cms

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, rpi]

    steps:
      - uses: actions/checkout@v6

      - name: Set .env
        run: |
          cat > .env << EOF

          HOST=${{ secrets.HOST }}
          PORT=${{ secrets.PORT }}
          PUBLIC_URL=${{ secrets.PUBLIC_URL }}

          APP_KEYS=${{ secrets.APP_KEYS }}
          API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}
          ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
          TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}
          ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}

          DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_SSL=${{ secrets.DATABASE_SSL }}
          DATABASE_FILENAME=${{ secrets.DATABASE_FILENAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}

          NODE_ENV=production
          EOF

      - name: Build and deploy
        run: |
          docker compose --profile nuxtie-strapi up -d --build

      - name: Import strapi config
        run: |
          sleep 20
          docker compose exec -T strapi npm run cs:import
